config/routes.rb
Rails.application.routes.draw do
  
  resources :categories

  resources :students do 
   resources :gradings do
  end
    collection do
      get :rate_students
    end
  end

  resources :judges

  devise_for :users

  get 'ratings/home'

  get 'ratings/profile'
  
  get 'ratings/dashboard'

  get 'ratings/about'

  get 'ratings/sign_up'

  get 'ratings/sign_in'

  devise_scope :user do

  get "/login" => "devise/sessions#new"

  get "/signup" => "devise/registrations#new"

  authenticated :user do
    root :to => 'ratings#dashboard'
    get 'ratings/judge_dashboard'
  end
  unauthenticated :user do
    root :to => 'ratings#index', as: :unauthenticated_root
  end
end

end

app/models/ability.rb
class Ability
  include CanCan::Ability
 
  def initialize(user)
      
    user ||= User.new
    if user.role == 'admin'
        can :manage, :all
    else
        can [:dashboard]
    end
    
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
	validates :name, :presence=>true
end

app/models/grading.rb
class Grading < ActiveRecord::Base
	validates :number, :presence=>true, :numericality=>{:less_than_or_equal_to=>10}
	validates_length_of :number, :minimum => 1, :maximum =>10 
	belongs_to :student
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/student.rb
class Student < ActiveRecord::Base
	has_many :gradings
	validates :phone_number, :presence=>true, :numericality=>true
	validates_length_of :phone_number, :presence=>true, :minimum =>10, :maximum=>10
	validates :full_name , :presence=>true
	validates :email_address , :presence=>true	
end

app/models/user.rb
class User < ActiveRecord::Base
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	validates :phone_number, :presence=>true, :numericality=>true
	validates_length_of :phone_number, :presence=>true, :minimum =>10, :maximum=>10 
  has_attached_file :image
  validates :image, :presence=>true
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]       
 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    role = "admin"
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:address, :email, :password, :phone_number, :image, :role) }
  end

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to ratings_judge_dashboard_path, :alert => exception.message
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  
  layout "dashboard"
  def index
  end

  def show
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(set_db_field)
    if @category.save
      flash[:message] = "Category Sucessfully created"
      redirect_to new_category_path
    else
      flash[:message] = "Sorry category could not create"
      render "new"
    end
  end

  private def set_db_field
     params.require(:category).permit(:name) 
  end

end

app/controllers/gradings_controller.rb
class GradingsController < ApplicationController
  
  layout "dashboard"
  def index
    @student = Student.find(params[:student_id])
    @gradings = @student.gradings
  end

  def new
    @categories = Category.all
    @student = Student.find(params[:student_id])
    @grading = Grading.new
  end

  def create
    @student = Student.find(params[:student_id])
    @grading = @student.gradings.new(set_db_field)
    if @grading.save
      flash[:message]= "Grade for #{@student.full_name} Sucessfully added"
      redirect_to new_student_grading_path
    else
      flash[:error]= @grading.errors.full_messages
      redirect_to new_student_grading_path 
    end 
  end

  private def set_db_field
    params.require(:grading).permit(:name, :number, :judge_by)
  end
end

app/controllers/judges_controller.rb
class JudgesController < ApplicationController
  
	layout "dashboard"
  def index
  end

  def new
  	@judge = User.new
  end

  def create
  	@judge = User.new(set_db_field)
  	if @judge.save
  	else
      flash[:error]=@judge.errors.full_messages
      redirect_to new_judge_path
  	end
  end

  private def set_db_field
  	params.require(:user).permit(:email, :password, :address, :phone_number, :image)
	end

end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  

  before_action :authenticate_user!, :only => [:dashboard]
  layout "rating"
	def index
		@header = 'header'
	end

  def dashboard
  	@header = 'dashboard_header'
    authorize! :dashboard, @header
  end

  def profile
    admin_id = current_user.id
    @admin_profile = User.find(admin_id)
    @header = 'dashboard_header'
  end

  def judge_dashboard
    @header = 'judge_dashboard'
  end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  
  layout "dashboard"
  def index
    @students = Student.all
  end

  def new
    @student = Student.new
    authorize! :dashboard, @student
  end

  def create
    @student = Student.new(set_db_field)
    authorize! :dashboard, @student
    if @student.save
      flash[:msg]="Student Sucessfully Created"
      render "new"
    else
      render "new"
    end
  end

  def destroy
    @student = Student.find(params[:id])
    if @student.destroy
      flash[:msg]="#{@student.full_name}  deleted"
      redirect_to students_path
    end
  end

  private def set_db_field
    params.require(:student).permit(:full_name, :email_address, :phone_number)
  end

  def rate_students
    @students = Student.all
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
	layout "dashboard"
  def index
  end

  def show
  end

  def edit
  end

  def delete
  end

  def new
  end

  def create
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/gradings_helper.rb
module GradingsHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/create.html.erb
<h1>Categories#create</h1>
<p>Find me in app/views/categories/create.html.erb</p>

app/views/categories/destroy.html.erb
<h1>Categories#destroy</h1>
<p>Find me in app/views/categories/destroy.html.erb</p>

app/views/categories/edit.html.erb
<h1>Categories#edit</h1>
<p>Find me in app/views/categories/edit.html.erb</p>

app/views/categories/index.html.erb
<h1>Categories#index</h1>
<p>Find me in app/views/categories/index.html.erb</p>

app/views/categories/new.html.erb
<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
	<h1 class="page-header"> Welcome To Dashboard</h1>
	<div class="alert alert-success">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    <%if flash[:message]%>
    	<strong><%=flash[:message]%></strong>
    <%else%>
    	<strong>Enter Category Name to add Category</strong>
    <%end%>
  </div>
  <div class="error_form">
  	<%if @category.errors.any?%>
  		<%@category.errors.full_messages.each do |s|%>
  			<%=s%>
  		<%end%>
  	<%end%>
  </div>
	<br>
	<div class="form-group">
	<%=form_for @category, url: {:action=>"create"}, html:{:role=>"form"} do |f|%>
		<label for="email">Full Name:</label>
		<div class="form-group">
			<%=f.text_field :name, :class=>"form_control", :id=>"email"%>
		</div>
		<div class="form-group">
			<%=f.submit("Submit", :class=>"btn btn-primary")%>
		</div>
	<%end%>
	</div>
</div>

app/views/categories/show.html.erb
<h1>Categories#show</h1>
<p>Find me in app/views/categories/show.html.erb</p>

app/views/gradings/create.html.erb
<h1>Gradings#create</h1>
<p>Find me in app/views/gradings/create.html.erb</p>

app/views/gradings/destroy.html.erb
<h1>Gradings#destroy</h1>
<p>Find me in app/views/gradings/destroy.html.erb</p>

app/views/gradings/edit.html.erb
<h1>Gradings#edit</h1>
<p>Find me in app/views/gradings/edit.html.erb</p>

app/views/gradings/index.html.erb
<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
	<div class="alert alert-success">
	  <strong>Student <%=@student.full_name%> Grading Details</strong>
  </div>
	<div class="form-group">
		<table class="table table-hover">
			<thead>
     		<tr>
       	<th>Category Name</th>
       	<th>Total Marks</th>
        <th>Marks On Scale 1-10</th>
      </tr>
    	</thead>
			<tbody>
			<%sum =0%>
				<%@gradings.each do |s|%>
      	<tr>
       	<td><%=s.name%></td>
      	<td>10</td>
      	<td><%=s.number%></td>
      	<%sum+=s.number%>
      	</tr>
			<%end%>
    </tbody>
  </table>
  <h4>Total Number of categories judged <%=@gradings.count%> </h4>
  <h4>Total Number of Marks Obtained <%=sum%> </h4>
  <h4>Marks Calculated in total marks Ten <%=sum/@gradings.count%> </h4>
	</div>
</div>

app/views/gradings/new.html.erb
<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
	<div class="alert alert-success">
    	<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    	<%if flash[:message]%>
    		<strong><%=flash[:message]%></strong>
    	<%else%>
    		<strong>Category list for judging student</strong>
    	<%end%>
  </div>
  <div class = "error_form">
  <% if flash[:error]%>
  	<%flash[:error].each do |s|%>
  		<%=s%>
  	<%end%>
  <%end%>
  </div>
	<div class="form-group">
		<table class="table table-hover">
		<thead>
     <tr>
       <th>Category Name</th>
        <th>Marks On Scale 1-10</th>
        <th>Submit</th>
      </tr>
    </thead>
		<tbody>
			<%@categories.each do |s|%>
	      <tr>
					<%= form_for @grading, url: student_gradings_path(@student.id) do |f| %>
		        <td><%=f.text_field :name, :class=>"form_control", :readonly=>true, :value=>s.name%></td>
		      	<td><%=f.text_field :number, :class=>"form_control"%></td>
		      	<td><%=f.submit("Submit", :class=>"btn btn-primary")%></td>
	   			<%end%>
	      </tr>
			<%end%>
    </tbody>
  </table>
</div>
</div>

app/views/judges/delete.html.erb
<h1>Users#delete</h1>
<p>Find me in app/views/users/delete.html.erb</p>

app/views/judges/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/judges/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/judges/new.html.erb
<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
	<h1 class="page-header"> Enter All Values to add judge</h1>
	<div class="error_form">
  <% if flash[:error]%>
  	<%flash[:error].each do |s|%>
  		<%=s%><br>
  	<%end%>
  <%end%>
  </div>
	<div class="form-group">
	<%=form_for @judge, url: {:action=>"create"}, html:{:role=>"form"} do |f|%>
		<label for="email">Email Address:</label>
		<div class="form-group">
		<%=f.text_field :email, :class=>"form_control", :id=>"email"%>
		</div>
		<label for="pwd">Password:</label>
		<div class="form-group">
		<%=f.text_field :password, :class=>"form_control", :id=>"pwd"%>
		</div>
		<label for="pwd">Address:</label>
		<div class="form-group">
		<%=f.text_field :address, :class=>"form_control"%>
		</div>
		<label for="pwd">Phone No.</label>
		<div class="form-group">
		<%=f.text_field :phone_number, :class=>"form_control"%>
		</div>
		<label for="pwd">Upload Picture</label>
		<div class="form-group">
		<%=f.file_field :image, :class=>"form_control"%>
		</div>
		<div class="form-group">
		<%=f.submit("Submit", :class=>"btn btn-primary")%>
		</div>
	<%end%>
</div>
</div>

app/views/judges/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rating</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= yield %>
</body>
</html>

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rating</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%if current_user.role=="admin"%>
	<%=render "ratings/dashboard_header"%>
	<%else%>
	<%=render "ratings/judge_dashboard"%>
	<%end%>
	<%= yield %>
</body>
</html>

app/views/layouts/rating.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rating</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render @header %>
	<%= yield %>
	<%= render "footer" %>
</body>
</html>

app/views/ratings/_dashboard_header.html.erb
<nav class="navbar-inverse navbar-fixed-top" id="dashboard_nav">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Online Rating System</a>
    </div>
  </div>
</nav>
<div class="container-fluid">
  <div class="row" >
    <div class="col-sm-3 col-md-2 sidebar navbar-collapse collapse" id="dashboard_navbar">
      <ul class="nav nav-sidebar">
        <li class="active"><%=link_to("Dashboard", root_url)%></li>
        <li><%=link_to("View Profile", ratings_profile_path)%></li>
      </ul>
      <ul class="nav nav-sidebar">
        <li><%=link_to("Add Judges", new_judge_path)%></li>
        <li><%=link_to("Add Students", new_student_path)%></li>
        <li><%=link_to("View Students", students_path)%></li>
        <li><%=link_to("Add Category", new_category_path )%></li>
      </ul>
      <ul class="nav nav-sidebar">
        <li> <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
      </ul>
    </div>
  </div>
</div>

app/views/ratings/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      </button>
      <%=link_to("Rating System",unauthenticated_root_path, :class=>"navbar-brand")%>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%=link_to("Login",login_path)%></li>
        <li><%=link_to("Sign up",signup_path)%></li>
      </ul>
    </div>
  </div>
</nav>

app/views/ratings/_judge_dashboard.html.erb
<nav class="navbar-inverse navbar-fixed-top" id="dashboard_nav">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Online Rating System</a>
    </div>
  </div>
</nav>
<div class="container-fluid">
  <div class="row" >
    <div class="col-sm-3 col-md-2 sidebar navbar-collapse collapse" id="dashboard_navbar">
      <ul class="nav nav-sidebar">
        <li class="active"><a href="#"> Dashboard <span class="sr-only">(current)</span></a></li>
      </ul>
      <ul class="nav nav-sidebar">
      <li><%=link_to("Rate Students", rate_students_students_path)%></li>
      </ul>
      <ul class="nav nav-sidebar">
        <li> <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
      </ul>
    </div>
  </div>
</div>

app/views/ratings/about.html.erb
<h1>Ratings#about</h1>
<p>Find me in app/views/ratings/about.html.erb</p>

app/views/ratings/dashboard.html.erb
<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
  <h1 class="page-header"> Welcome To Dashboard</h1>
</div>

app/views/ratings/home.html.erb
<h1>Ratings#home</h1>
<p>Find me in app/views/ratings/home.html.erb</p>

app/views/ratings/index.html.erb
<div class="index_content">
  <div class="row" id="row_content">
    <div class="col-sm-6"id="right_form_content">
      <h2> The fast and easy way to translate and deliver your online content
      Over 15,000 professionals waiting to translate your content in up to 30 languages.
      </h2>
      <br>
      <button class="btn btn-primary btn-lg">Create Account </button>
    </div>
    <div class="col-sm-5" id="content_img">
    </div>
  </div>
  <div class="col-sm-12">
    <h3>Features Of Online Rating Management System</h3>
  </div>
  <div class="col-sm-4">
    <h3>Features</h3>
    <p>Excel Report Generate For Admin Excel Report Generate F Generate For Generate For Generate Foror Admin</p>
  </div>
  <div class="col-sm-4">
    <h3>Features</h3> 
    <p>Excel Report Generate F Generate For Generate For Generate Foror Admin Excel Report Generate F Generate For Generate For Generate Foror Admin</p>  
  </div>
  <div class="col-sm-4">
    <h3>Features</h3>
    <p>Excel Report Generate For Admin Excel Report Generate F Generate For Generate For Generate Foror Admin</p>
  </div>
</div>

app/views/ratings/profile.html.erb
<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
	<div class="col-sm-4">
		<%=image_tag @admin_profile.image.url,:class=>"profile_img"%>
	</div>
	<div class="col-sm-6">
		<div class="profile_detail">
			<p>Email:
			<%=@admin_profile.email%>
			</p>
		</div>
		<div class="profile_detail">
			<p>Address:
			<%=@admin_profile.address%>
			</p>
		</div>
		<div class="profile_detail">
			<p>Phone Number:
			<%=@admin_profile.phone_number%>
			</p>
		</div>
	</div>
</div>

app/views/ratings/sign_in.html.erb
<h1>Ratings#sign_in</h1>
<p>Find me in app/views/ratings/sign_in.html.erb</p>

app/views/ratings/sign_up.html.erb
<h1>Ratings#sign_up</h1>
<p>Find me in app/views/ratings/sign_up.html.erb</p>

app/views/students/create.html.erb
<h1>Students#create</h1>
<p>Find me in app/views/students/create.html.erb</p>

app/views/students/delete.html.erb
<h1>Students#delete</h1>
<p>Find me in app/views/students/delete.html.erb</p>

app/views/students/edit.html.erb
<h1>Students#edit</h1>
<p>Find me in app/views/students/edit.html.erb</p>

app/views/students/index.html.erb
<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
	<h1 class="page-header"> Student List</h1>
	<h2> </h2>
	<table class="table table-hover">
		<thead>
     <tr>
       <th>Full Name</th>
        <th>Email</th>
        <th>Phone No</th>
        <th>Edit</th>
        <th>Delete</th>
      </tr>
    </thead>
		<tbody>
      <%@students.each do |s|%>
      <tr>
        <td><%=s.full_name%></td>
        <td><%=s.email_address%></td>
        <td><%=s.phone_number%></td>
        <td><button class="btn btn-primary">Edit</button></td>
      	<td><%= button_to "Delete", student_path(s.id), :method => "delete",:class =>"btn btn-primary",data: { confirm: 'Are you sure?'} %>
      </tr>
   		<%end%>
    </tbody>
  </table>
</div>

app/views/students/new.html.erb
<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
	<h1 class="page-header"> Welcome To Dashboard</h1>
	<div class="error_form">
	<%if @student.errors.any?%>
	<%@student.errors.full_messages.each do |s|%>
	<%=s%><br>
	<%end%>
	<%end%>
	</div>
	<%if flash[:msg]%>
		<%=flash[:msg]%>
	<%end%>
	<div class="form-group">
	<%=form_for @student, url: {:action=>"create"}, html:{:role=>"form"} do |f|%>
		<label for="email">Full Name:</label>
		<div class="form-group">
		<%=f.text_field :full_name, :class=>"form_control", :id=>"email"%>
		</div>
		<label for="pwd">Email Address:</label>
		<div class="form-group">
		<%=f.text_field :email_address, :class=>"form_control", :id=>"pwd"%>
		</div>
		<label for="pwd">Phone Number:</label>
		<div class="form-group">
		<%=f.text_field :phone_number, :class=>"form_control"%>
		</div>
		<div class="form-group">
		<%=f.submit("Submit", :class=>"btn btn-primary")%>
		</div>
	<%end%>
</div>
</div>

app/views/students/rate_students.html.erb
<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
	<h1 class="page-header"> Student List</h1>
	<h2> </h2>
	<table class="table table-hover">
		<thead>
     <tr>
       <th>Full Name</th>
        <th>Email</th>
        <th>Phone No</th>
        <th>Edit</th>
        <th>View Grading History</th>
      </tr>
    </thead>
		<tbody>
			<%@students.each do |s|%>
      <tr>
        <td><%=s.full_name%></td>
        <td><%=s.email_address%></td>
        <td><%=s.phone_number%></td>
        <td><%= link_to "Grade Students", new_student_grading_path(s.id)%></td>
        <td><%= link_to "View Grading", student_gradings_path(s.id)%></td>
      </tr>
   		<%end%>
    </tbody>
  </table>
</div>

app/views/students/show.html.erb
<h1>Students#show</h1>
<p>Find me in app/views/students/show.html.erb</p>